function turtleDraw( canvas )
turtlePen( false, canvas )
turtleForward( 0.5, canvas )
turtlePen( true, canvas )
turtleRotate( -150, canvas )
turtleForward( 1, canvas )
turtleRotate( -120, canvas )
turtleForward( 1, canvas )
turtleRotate( -120, canvas )
turtleForward( 1, canvas )
turtleRotate( 30, canvas )
turtlePen( false, canvas )
turtleForward( 0.5, canvas )
end
